// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_notes_id_ from "./routes/api/notes/[id].ts";
import * as $api_notes_index from "./routes/api/notes/index.ts";
import * as $api_notes_new from "./routes/api/notes/new.ts";
import * as $index from "./routes/index.tsx";
import * as $notes_id_ from "./routes/notes/[id].tsx";
import * as $notes_new from "./routes/notes/new.tsx";
import * as $AddNote from "./islands/AddNote.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $NoteEditor from "./islands/NoteEditor.tsx";
import * as $NoteList from "./islands/NoteList.tsx";
import * as $SearchInput from "./islands/SearchInput.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/notes/[id].ts": $api_notes_id_,
    "./routes/api/notes/index.ts": $api_notes_index,
    "./routes/api/notes/new.ts": $api_notes_new,
    "./routes/index.tsx": $index,
    "./routes/notes/[id].tsx": $notes_id_,
    "./routes/notes/new.tsx": $notes_new,
  },
  islands: {
    "./islands/AddNote.tsx": $AddNote,
    "./islands/Counter.tsx": $Counter,
    "./islands/NoteEditor.tsx": $NoteEditor,
    "./islands/NoteList.tsx": $NoteList,
    "./islands/SearchInput.tsx": $SearchInput,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
